WIDTH = 800
HEIGHT = 600
FPS = 60

ISLAND_WIDTH = 150
ISLAND_HEIGHT = 200

ATTACK_POINT_BOX_WIDTH = 100
ATTACK_POINT_BOX_HEIGHT = 50

DEFENSE_POINT_BOX_WIDTH = 100
DEFENSE_POINT_BOX_HEIGHT = 50

TEXT_FONT = "Avenir"
HEALTH_TEXT_SIZE = 20
ATTACK_TEXT_SIZE = 20
DEFENSE_TEXT_SIZE = 20

# Variables :

HEALTH_RED = 100
HEALTH_BLUE = 100
ATTACK_POINT_RED = 1
ATTACK_POINT_BLUE = 1
DEFENSE_POINT_RED = 1
DEFENSE_POINT_BLUE = 1
DEFENSE_RED_ACTIVATED = 0
DEFENSE_BLUE_ACTIVATED = 0

# Initial player turn :
PLAYER_TURN_RED = 1
PLAYER_TURN_BLUE = 0
